<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- Chasis & Wheels -->
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <xacro:property name="wheel_offset_x" value="${base_length / 2.0}" />
    <xacro:property name="wheel_offset_y" value="${base_width / 2.0 + wheel_length / 2.0}" />
    <xacro:property name="base_origin_z" value="${base_height / 2.0}" />
    
    <xacro:property name="axle_eff_limit" value="5.12766"/>
    <xacro:property name="axle_vel_limit" value="244.8696"/>

    <xacro:property name="chasis_weight_kgs" value="5" />
    <xacro:property name="wheel_weight_kgs" value="0.5" />

    <!-- LiDar -->
    <xacro:property name="lidar_radius" value="0.05"/>
    <xacro:property name="lidar_length" value="0.04"/>
    <xacro:property name="lidar_mass" value="0.1"/>

    <!-- Camera -->
    <xacro:property name="camera_length" value="0.03"/>
    <xacro:property name="camera_width" value="0.03"/>
    <xacro:property name="camera_height" value="0.01"/>

</robot>